services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGHOST=${POSTGRES_HOST}
      - PGPORT=${POSTGRES_PORT}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: bogemad/mgt-xcitri-web:${TAG:-latest}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - init_flag:/var/lib/db_init
    entrypoint: >
      bash -lc "
        set -o allexport; source .env; set +o allexport;
        #Build server if not done already
        if [ ! -f \"${DB_INIT_FLAG}\" ]; then
          echo '⚙️  First‐run: initializing database...';
          find . -type f -print0 | xargs -0 dos2unix > /dev/null;
          cd setup;
          bash setup_new_database.ssh Xcitri_inputs.setupPath;
        else
          echo '✅ Skipping DB init (flag exists at ${DB_INIT_FLAG})';
        fi;
        # Conda init  
        . /opt/conda/etc/profile.d/conda.sh  
        conda activate mgtenv
        # Finally start the server
        cd /app/Mgt/Mgt
        python manage.py runserver 0.0.0.0:8000 --settings Mgt.settings_template
      "

volumes:
  postgres_data:
  init_flag:
